version: "3"
services:
  app:
    command: bash -c "rm -f tmp/pids/server.pid &&  bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/borobo
      - bundle:/usr/local/bundle
      - public-data:/borobo/public
      - tmp-data:/borobo/tmp
      - log-data:/borobo/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
  nginx:
    build: containers/nginx
    ports:
      - "8080:80"
    volumes:
      - public-data:/borobo/public
      - tmp-data:/borobo/tmp
    tty: true
volumes:
  bundle:
  public-data:
  tmp-data:
  db_data:
  log-data:
