version: "3"
services:
  app: &app
    command: bash -c "rm -f tmp/pids/server.pid &&  bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - .:/borobo
      - bundle:/usr/local/bundle
      - public-data:/borobo/public
      - tmp-data:/borobo/tmp
      - log-data:/borobo/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
  webpacker:
    <<: *app
    build: .
    command: bundle exec bin/webpack-dev-server
    depends_on:
      - app
    ports:
      - "3035:3035"
    tty: false
volumes:
  bundle:
  public-data:
  tmp-data:
  db_data:
  log-data:
